name: update-packege-data

on:
  push:
    #schedule:
    #- cron: 0/10 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt install xz-utils
      - run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam upgrade
          opam install satyrographos-snapshot-stable || true
          satyrographos install
          #| - run: rm -rf docs
          #- run: cp -rL ~/.satysfi/dist/docs .
        #- run: git clone https://github.com/na4zagin3/satyrographos-repo.git
        #- run: opam install opam-file-format yojson
      #- run: make run
      #- run: git config user.name github-actions
      #- run: git config user.email github-actions@github.com
      #- run: git add data.json
      #- run: git add docs/*
      #- run: git commit -m "update package data"
      #- run: git push

